/**
 * ============================================================================
 * TURBO KART — main entry point / integrator
 * ============================================================================
 * Owned by the orchestrator. Wires every subsystem together through the shared
 * event bus and the frozen contract in `src/contracts.js`.
 *
 * Subsystem agents: DO NOT EDIT THIS FILE. If your module needs a different
 * call signature, document it in your report instead.
 * ============================================================================
 */
import * as THREE from 'three';
import { bus } from './core/events.js';
import {
  EVENTS, RACE, MODES, CHARACTERS, getCharacter, getTrackMeta,
  createInputState, DEFAULT_QUALITY, DEFAULT_DIFFICULTY, DEFAULT_CAMERA_MODE,
} from './contracts.js';

import { Engine } from './core/engine.js';
import { createInput } from './core/input.js';
import { Kart } from './kart/kart.js';
import { getTrack } from './track/trackData.js';
import { TrackBuilder } from './track/trackBuilder.js';
import { createEnvironment } from './track/environment.js';
import { AIDriver } from './ai/aiDriver.js';
import { RaceManager } from './race/raceManager.js';
import { ItemSystem } from './items/itemSystem.js';
import { HUD } from './ui/hud.js';
import { Menus } from './ui/menus.js';
import { AudioManager } from './audio/audio.js';
import { Effects } from './fx/effects.js';
import { PostFX } from './fx/postprocessing.js';

const bootStatus = (msg, pct) => {
  const el = document.getElementById('boot-status');
  const bar = document.getElementById('boot-bar-fill');
  if (el) el.textContent = msg;
  if (bar && typeof pct === 'number') bar.style.width = `${Math.round(pct * 100)}%`;
};

class TurboKart {
  constructor() {
    this.canvas = document.getElementById('game-canvas');
    this.uiRoot = document.getElementById('ui-root');
    this.state = 'boot';
    this.quality = DEFAULT_QUALITY;
    this.cameraMode = DEFAULT_CAMERA_MODE;
    this.settings = { quality: DEFAULT_QUALITY, master: 0.9, music: 0.6, sfx: 0.9, cameraMode: DEFAULT_CAMERA_MODE };
    this.config = { trackId: getTrackMeta().id, characterId: CHARACTERS[0].id, difficulty: DEFAULT_DIFFICULTY, mode: MODES.GP };
    this.race = null; // active race bundle
    this.paused = false;
    this.lastTime = 0;
    this.frame = 0;
  }

  // ---------------------------------------------------------------- boot ----
  async boot() {
    bootStatus('Starting engine…', 0.1);
    this.engine = new Engine({ canvas: this.canvas, quality: this.quality });

    bootStatus('Warming up audio…', 0.25);
    this.audio = new AudioManager({ bus, settings: this.settings });

    bootStatus('Building interface…', 0.4);
    this.hud = new HUD({ bus, container: this.uiRoot });
    this.menus = new Menus({ bus, container: this.uiRoot, characters: CHARACTERS, settings: this.settings });

    bootStatus('Preparing effects…', 0.55);
    this.effects = new Effects({ bus, THREE, scene: this.engine.scene, camera: this.engine.camera });
    this.postfx = new PostFX({ THREE, renderer: this.engine.renderer, scene: this.engine.scene, camera: this.engine.camera, quality: this.quality });

    bootStatus('Connecting controls…', 0.7);
    this.input = createInput({ bus, domElement: this.canvas });

    this._wireEvents();

    bootStatus('Ready!', 1);
    this._setState('menu');
    this.menus.showTitle(this.config);

    // First-frame render so the menu has a backdrop.
    this.engine.render(this.postfx);
    requestAnimationFrame((t) => this.loop(t));
  }

  _wireEvents() {
    bus.on(EVENTS.UI_RACE_CONFIG, (cfg) => this.startRace({ ...this.config, ...cfg }));
    bus.on(EVENTS.UI_RESTART, () => this.startRace(this.config));
    bus.on(EVENTS.UI_QUIT, () => {
      this._disposeRace();
      this.paused = false;
      this._setState('menu');
      this.menus.showTitle(this.config);
      this.audio?.playMusic?.('menu');
    });
    bus.on(EVENTS.UI_PAUSE, () => this.setPaused(true));
    bus.on(EVENTS.UI_RESUME, () => this.setPaused(false));
    bus.on(EVENTS.UI_SETTINGS, (s) => this.applySettings(s));
    bus.on(EVENTS.RACE_COMPLETE, (payload) => this._onRaceComplete(payload));
    bus.on(EVENTS.RACE_COUNTDOWN, ({ value } = {}) => {
      if (value > 0) this.hud?.showCountdown?.(value);
      else this.hud?.showCountdown?.('GO!');
    });
    bus.on(EVENTS.RACE_START, () => {
      this.hud?.hideCountdown?.();
      this._setState('racing');
    });
  }

  // --------------------------------------------------------------- race -----
  startRace(config) {
    this.config = { ...this.config, ...config };
    this.menus?.hide?.();
    this.menus?.hidePause?.();
    this._disposeRace();
    bootStatus('Loading track…', 0.5);

    const meta = getTrackMeta(this.config.trackId);
    const trackDef = getTrack(this.config.trackId);
    const builder = new TrackBuilder({ THREE, trackDef, meta });
    const trackApi = builder.build();
    this.engine.scene.add(trackApi.group);
    this.engine.setTrack?.(trackApi); // shadow-camera fitting / ground queries

    const environment = createEnvironment({ THREE, trackApi, scene: this.engine.scene, quality: this.quality });
    if (environment?.group) this.engine.scene.add(environment.group);

    const mode = this.config.mode || MODES.GP;
    const solo = mode === MODES.TIME_TRIAL;
    const kartCount = solo ? 1 : RACE.KART_COUNT;
    const playerCharacter = getCharacter(this.config.characterId);

    /** @type {Kart[]} */
    const karts = [];
    /** @type {AIDriver[]} */
    const aiDrivers = [];

    // Player starts last (grid slot kartCount-1), AI fill the rest.
    const playerSlot = kartCount - 1;
    const aiCharacterIds = CHARACTERS.filter((c) => c.id !== playerCharacter.id).map((c) => c.id);

    for (let i = 0; i < kartCount; i++) {
      const isPlayer = i === playerSlot;
      const characterId = isPlayer
        ? playerCharacter.id
        : aiCharacterIds[(i + 1) % aiCharacterIds.length];
      const kart = new Kart({
        THREE, bus, trackApi,
        isPlayer,
        characterId,
        startIndex: i,
        difficulty: this.config.difficulty,
        quality: this.quality,
      });
      this.engine.scene.add(kart.object3D);
      karts.push(kart);
      if (!isPlayer) {
        aiDrivers.push(new AIDriver({ THREE, bus, kart, trackApi, difficulty: this.config.difficulty, index: i }));
      }
    }

    const raceManager = new RaceManager({ bus, THREE, karts, trackApi, laps: solo ? RACE.LAPS : meta.laps, playerKart: karts[playerSlot], solo });
    const itemSystem = solo ? null : new ItemSystem({ bus, THREE, scene: this.engine.scene, karts, trackApi, playerKart: karts[playerSlot], difficulty: this.config.difficulty });

    this.race = { trackApi, environment, karts, aiDrivers, raceManager, itemSystem, builder, meta, solo };

    this.hud?.setTrack?.(trackApi);
    this.hud?.show?.();
    this.hud?.setMode?.(mode);
    this.effects?.setTrack?.(trackApi);

    this.paused = false;
    this._setState('countdown');
    raceManager.start();
    this.audio?.playMusic?.(meta.theme);
    this.input?.setEnabled?.(true);
  }

  _disposeRace() {
    const r = this.race;
    if (!r) return;
    this.input?.setEnabled?.(false);
    for (const k of r.karts) {
      k.dispose?.();
      if (k.object3D?.parent) k.object3D.parent.remove(k.object3D);
    }
    for (const a of r.aiDrivers) a.dispose?.();
    r.itemSystem?.dispose?.();
    r.raceManager?.dispose?.();
    r.environment?.dispose?.();
    if (r.trackApi?.group?.parent) r.trackApi.group.parent.remove(r.trackApi.group);
    r.trackApi?.dispose?.();
    r.builder?.dispose?.();
    this.engine?.setTrack?.(null);
    this.effects?.setTrack?.(null);
    this.hud?.hide?.();
    this.race = null;
  }

  _onRaceComplete(payload) {
    const standings = payload?.standings || [];
    this._setState('results');
    this.hud?.hide?.();
    const player = this.race?.karts?.find((k) => k.isPlayer);
    const place = standings.find((s) => s?.kart === player)?.place ?? 1;
    this.menus.showResults(standings, { config: this.config, place, mode: this.config.mode });
    this.audio?.playMusic?.(place === 1 ? 'victory' : 'results');
  }

  // --------------------------------------------------------------- state ----
  _setState(next) {
    if (this.state === next) return;
    const prev = this.state;
    this.state = next;
    bus.emit(EVENTS.GAME_STATE, { state: next, prev });
  }

  setPaused(on) {
    if (!this.race) return;
    this.paused = !!on;
    if (this.paused) {
      this.menus?.showPause?.(this.settings);
      this.input?.setEnabled?.(false);
    } else {
      this.menus?.hidePause?.();
      this.input?.setEnabled?.(true);
    }
  }

  applySettings(s = {}) {
    Object.assign(this.settings, s);
    this.quality = this.settings.quality;
    this.cameraMode = this.settings.cameraMode || this.cameraMode;
    this.engine?.setQuality?.(this.quality);
    this.postfx?.setQuality?.(this.quality);
    this.effects?.setQuality?.(this.quality);
    this.race?.environment?.setQuality?.(this.quality);
    this.race?.karts?.forEach((k) => k.setQuality?.(this.quality));
    this.audio?.setVolumes?.({ master: this.settings.master, music: this.settings.music, sfx: this.settings.sfx });
    this.hud?.setQuality?.(this.quality);
  }

  // ---------------------------------------------------------------- loop ----
  loop(now) {
    requestAnimationFrame((t) => this.loop(t));
    const dt = Math.min(0.05, this.lastTime ? (now - this.lastTime) / 1000 : 0.016);
    this.lastTime = now;
    this.frame++;
    try {
      this._update(dt);
    } catch (err) {
      console.error('[main] update error:', err);
    }
    try {
      this.engine.render(this.postfx);
    } catch (err) {
      console.error('[main] render error:', err);
      this.engine.render(); // fallback without post-processing
    }
  }

  _update(dt) {
    const r = this.race;
    const active = this.state === 'racing' || this.state === 'countdown' || this.state === 'results';

    this.input?.update?.(dt, { active: !this.paused && active });

    if (r && !this.paused) {
      const player = r.karts.find((k) => k.isPlayer);
      const playerInput = this.input?.state || createInputState();

      // Karts
      for (const kart of r.karts) {
        if (kart.isPlayer) {
          kart.update(dt, this.state === 'racing' || this.state === 'results' ? playerInput : this._countdownInput(playerInput));
        }
      }
      for (const ai of r.aiDrivers) {
        const inp = ai.update(dt, { raceManager: r.raceManager, karts: r.karts, state: this.state });
        ai.kart.update(dt, inp);
      }

      r.raceManager.update(dt);
      r.itemSystem?.update(dt, { raceManager: r.raceManager });
      r.environment?.update?.(dt, this.engine.camera);
      this.effects?.update?.(dt, r.karts, r.trackApi);

      const standings = r.raceManager.standings || [];
      const playerStanding = standings.find((s) => s?.kart === player);
      this.hud?.update?.(dt, {
        state: this.state,
        kart: player,
        speed: Math.abs(player?.state?.speed || 0),
        lap: player?.lap || 1,
        laps: r.raceManager.laps || RACE.LAPS,
        place: playerStanding?.place || r.karts.length,
        totalKarts: r.karts.length,
        standings,
        karts: r.karts,
        item: r.itemSystem?.getItemFor?.(player) || null,
        roulette: r.itemSystem?.isRolling?.(player) || false,
        boostCharge: player?.state?.driftCharge || 0,
        drifting: !!player?.state?.drifting,
        boosting: !!player?.state?.boosting,
        raceTime: r.raceManager.raceTime || 0,
        countdown: r.raceManager.countdownValue ?? null,
        wrongWay: !!player?.state?.wrongWay,
        offRoad: !!player?.state?.offRoad,
        mode: this.config.mode,
        quality: this.quality,
      });
    }

    if (r) {
      this.engine.updateCamera(dt, r.karts.find((k) => k.isPlayer), {
        mode: this.cameraMode,
        lookBack: !!this.input?.state?.lookBack,
        paused: this.paused,
      });
      this.audio?.update?.(dt, { kart: r.karts.find((k) => k.isPlayer), camera: this.engine.camera, state: this.state });
    } else {
      this.engine.updateMenuCamera?.(dt);
      this.audio?.update?.(dt, { kart: null, camera: this.engine.camera, state: this.state });
    }
  }

  /** During the countdown only throttle input is honoured (rocket start). */
  _countdownInput(inp) {
    return { ...inp, steer: 0, drift: false, useItem: false, brake: 0 };
  }
}

const game = new TurboKart();
window.__TURBO_KART__ = game;
game.boot().catch((err) => {
  console.error('[main] boot failed:', err);
  bootStatus(`Boot failed: ${err?.message || err}`, 0);
});
